// <auto-generated />
namespace TDC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ShockUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShockUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201412061707074_ShockUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
